export default {
  SET_DARK_MODE: 'SET_DARK_MODE',
  SET_FAVORITE_FORECASTS: 'SET_FAVORITE_FORECASTS',
  SET_SELECTED_LOCATION: 'SET_SELECTED_LOCATION',
  SET_SELECTED_TAB_INDEX: 'SET_SELECTED_TAB_INDEX',
};
